archive: {{ pulsar_home }}/pulsar-io-cassandra-sink-connector/{{ keyspaces_sink_nar_file }}
tenant: public
namespace: default
name: ${SINK_CONNECTOR_NAME}
inputs:
  - ${PULSAR_DATA_TOPIC_NAME}
subs-position: ${TOPIC_READ_FROM}
configs:
  roots : "cassandra.{{ region }}.amazonaws.com:9142"
  keyspace : "${KEYSPACE_NAME}"
  tableName : "${KEYSPACES_TABLE_NAME}"
  configFilePath: "{{ pulsar_home }}/pulsar-io-cassandra-sink-connector/keyspaces-sink-secret-manager-conf.conf"
  nullValueAction: "DELETE"